services:  
  promise-env:
    build: .
    image: hpc-promise-env:latest
    container_name: promise_runner
    volumes:
      - .:/app
    ulimits:
      stack: 67108864
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16G

    tty: true
    stdin_open: true
    command: /bin/bash