NVCC ?= nvcc
CUDA_ARCH ?= sm_90
TARGET ?= backprop_cuda

.PHONY: all clean
all: $(TARGET)

$(TARGET): backprop_cuda.cu ../cuda_backprop_h100.cuh ../../cuda_common/h100_mixed_precision.cuh
	$(NVCC) -O3 -std=c++17 -arch=$(CUDA_ARCH) backprop_cuda.cu -o $(TARGET)

clean:
	$(RM) $(TARGET)
