NVCC ?= nvcc
CUDA_ARCH ?= sm_90
TARGET ?= hotspot_cuda

.PHONY: all clean
all: $(TARGET)

$(TARGET): hotspot_cuda.cu ../cuda_hotspot_h100.cuh ../../cuda_common/h100_mixed_precision.cuh
	$(NVCC) -O3 -std=c++17 -arch=$(CUDA_ARCH) hotspot_cuda.cu -o $(TARGET)

clean:
	$(RM) $(TARGET)
